name = "cf-worker-ai-stable-diffusion"
main = "src/index.ts"
compatibility_date = "2023-02-03"
node_compat = true
account_id = "34018b4941d2988926ae8ac16f096d26"

routes = [
    { pattern = "worker-ai.boris1993.com/stable-diffusion", zone_name = "boris1993.com" }
]

[ai]
binding = "AI"
